COMPLIANCE_MUSIC = {
    "handel": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1759, all works and writings public domain.",
        "production_ready": True,
    },
    "vivaldi": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1741, all works and writings public domain.",
        "production_ready": True,
    },
    "brahms": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1897, all works and writings public domain.",
        "production_ready": True,
    },
    "schubert": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1828, all works and writings public domain.",
        "production_ready": True,
    },
    "chopin": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1849, all works and writings public domain.",
        "production_ready": True,
    },
    "liszt": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1886, all works and writings public domain.",
        "production_ready": True,
    },
    "verdi": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1901, all works and writings public domain.",
        "production_ready": True,
    },
    "wagner": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1883, all works and writings public domain. High sensitivity due to Nazi appropriation and documented anti-Semitism.",
        "production_ready": True,
        "high_sensitivity": True,
    },
    "tchaikovsky": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1893, all works and writings public domain.",
        "production_ready": True,
    },
    "mahler": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1911, all works and writings public domain.",
        "production_ready": True,
    },
    "debussy": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1918, all works and writings public domain.",
        "production_ready": True,
    },
    "stravinsky": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1971. Works composed after 1928 may have active copyright in some jurisdictions. Writings and interviews require care. Character persona is clear.",
        "production_ready": True,
    },
    "bartok": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1945. Works from 1925 onward may have active copyright. Ethnomusicological transcriptions have complex IP status. Character persona is clear.",
        "production_ready": True,
    },
    "callas": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1977. Recordings subject to performance rights. Estate actively litigates likeness rights. Speak about her interpretive philosophy and documented views; avoid quoting recordings.",
        "production_ready": True,
    },
    "caruso": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1921. All recordings from his era are public domain in most jurisdictions. Character persona fully clear.",
        "production_ready": True,
    },
    "armstrong": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1971. Song compositions he co-wrote may have active copyrights. Recordings subject to performance rights. Character persona and documented views are clear.",
        "production_ready": True,
    },
    "ellington": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1974. Many compositions still under copyright, held by his estate. Recordings subject to performance rights. Character persona and documented views are clear.",
        "production_ready": True,
    },
    "coltrane": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1967. Compositions may still be under copyright. Recordings subject to performance rights. His documented spiritual and musical philosophy is well-sourced and clear.",
        "production_ready": True,
    },
    "parker": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1955. Some compositions still under copyright. Recordings subject to performance rights. Character persona well-documented through extensive interviews and contemporaries.",
        "production_ready": True,
    },
    "monk": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1982. Compositions likely still under copyright. Recordings subject to performance rights. Character persona documented through interviews and Robin D.G. Kelley biography.",
        "production_ready": True,
    },
    "holiday": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1959. 'Strange Fruit' rights are complex. Recordings subject to performance rights. High sensitivity due to traumatic biography; handle her story with care and dignity.",
        "production_ready": True,
        "high_sensitivity": True,
    },
    "fitzgerald": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1996. Songbook recordings subject to performance rights. Estate active. Character persona is well-documented and non-controversial.",
        "production_ready": True,
    },
    "mingus": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1979. Compositions held by Hal Leonard/Sue Mingus Music. Recordings subject to performance rights. High sensitivity for racial politics content — handle accurately and seriously.",
        "production_ready": True,
        "high_sensitivity": True,
    },
    "dylan": {
        "living": True,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Born 1941, still living. All compositions under copyright. Persona requires extra care — living public figure. Stick to documented public statements and well-known positions.",
        "production_ready": True,
        "high_sensitivity": True,
    },
    "simone": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 2003. Estate active and litigious regarding likeness. Compositions under copyright. Political content is well-documented; handle racial justice themes with accuracy and seriousness.",
        "production_ready": True,
        "high_sensitivity": True,
    },
    "elvis": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1977. Elvis Presley Enterprises aggressively protects likeness and name. Recordings subject to RCA/Sony rights. Cultural appropriation dimension requires accurate, non-whitewashed handling.",
        "production_ready": True,
        "high_sensitivity": True,
    },
    "aretha": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 2018. Estate active; no will created probate disputes. Recordings subject to Atlantic/Arista rights. Character persona is well-documented through interviews and authorized sources.",
        "production_ready": True,
    },
    "hendrix": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1970. Experience Hendrix LLC (family) aggressively protects likeness and musical estate. Recordings under copyright. Character persona well-documented through contemporaries and his own interviews.",
        "production_ready": True,
    },
    "ravi_shankar": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 2012. Estate active; Anoushka Shankar manages musical legacy. Compositions under copyright. Handle cultural transmission vs. appropriation themes with precision.",
        "production_ready": True,
    },
    "gould": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1982. Recordings held by Sony Classical. Essays and writings still under copyright. Estate (Estate of Glenn Gould) is active. Character persona extremely well-documented through his own prolific writings.",
        "production_ready": True,
    },
}
