COMPLIANCE_SOCIAL_SCIENCE = {
    "adam_smith": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1790. All works public domain.",
        "production_ready": True,
    },
    "ricardo": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1823. All works public domain.",
        "production_ready": True,
    },
    "malthus": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1834. All works public domain.",
        "production_ready": True,
    },
    "alfred_marshall": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1924. All works public domain.",
        "production_ready": True,
    },
    "veblen": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1929. All works public domain.",
        "production_ready": True,
    },
    "keynes": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1946. Primary works such as General Theory (1936) and Economic Consequences of the Peace (1919) are public domain in most jurisdictions. Some collected writings published posthumously by the Royal Economic Society may carry publisher copyright. No reproduction of those specific posthumous editions; paraphrase and reference to documented positions is clear.",
        "production_ready": True,
    },
    "schumpeter": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1950. Major works including Capitalism Socialism and Democracy (1942) and Theory of Economic Development (1911) are public domain in most jurisdictions. Some posthumous publications (History of Economic Analysis, 1954) may carry publisher copyright on the editorial compilation. Paraphrase and reference to documented positions is clear.",
        "production_ready": True,
    },
    "hayek": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 1992. Works published before approximately 1928 may be public domain in some jurisdictions; major works including The Road to Serfdom (1944), The Constitution of Liberty (1960), and Law Legislation and Liberty (1973–79) remain under copyright in most jurisdictions until 2062. Do not reproduce extended passages. Paraphrase and reference to documented positions is acceptable. Note: figure carries political controversy flag re. Chile/Pinochet.",
        "controversial": True,
        "production_ready": False,
    },
    "joan_robinson": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1983. Under the life-plus-70 rule applicable in most jurisdictions, works enter public domain in 2053. However, she died before 1928 cutoff does not apply. Copyright review needed for major works. Treating as review_needed pending jurisdiction confirmation.",
        "production_ready": True,
    },
    "ostrom": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 2012. Governing the Commons (1990) and subsequent works remain under copyright in all major jurisdictions. Do not reproduce extended passages. Paraphrase and reference to documented empirical findings and design principles is acceptable.",
        "production_ready": False,
    },
    "polanyi": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1964. Under life-plus-70 rule, works enter public domain in 2034 in EU; already public domain in some jurisdictions. The Great Transformation (1944) is in a transitional zone — treat as review_needed in EU contexts, mostly_clear in US contexts where published before 1927 cutoff does not apply but copyright renewal questions arise. Treating as mostly_clear for production purposes given 1944 US publication and copyright renewal status.",
        "production_ready": True,
    },
    "myrdal": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 1987. Works including An American Dilemma (1944) and Asian Drama (1968) remain under copyright in most jurisdictions until 2057. Do not reproduce extended passages. Paraphrase and reference to documented positions is acceptable.",
        "production_ready": False,
    },
    "coase": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 2013. Works including The Nature of the Firm (1937, journal article — may be public domain) and The Problem of Social Cost (1960, journal article) and The Firm the Market and the Law (1988) have varying copyright status. Journal articles from 1937 may be public domain depending on renewal; later works remain under copyright until 2083. Do not reproduce extended passages. Paraphrase acceptable.",
        "production_ready": False,
    },
    "herbert_simon": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 2001. Administrative Behavior (1947), Models of Man (1957), and Sciences of the Artificial (1969) remain under copyright in most jurisdictions until 2071. Do not reproduce extended passages. Paraphrase and reference to documented concepts (bounded rationality, satisficing) is acceptable.",
        "production_ready": False,
    },
    "douglass_north": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 2015. Structure and Change in Economic History (1981), Institutions Institutional Change and Economic Performance (1990), and Understanding the Process of Economic Change (2005) remain under copyright in all major jurisdictions until 2085. Do not reproduce extended passages. Paraphrase acceptable.",
        "production_ready": False,
    },
    "rawls": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 2002. A Theory of Justice (1971) and Political Liberalism (1993) remain under copyright in all major jurisdictions until 2072. Do not reproduce extended passages. Paraphrase and reference to documented philosophical positions is acceptable.",
        "production_ready": False,
    },
    "goffman": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1982. Under life-plus-70 rule, works enter public domain in 2052 in EU. In US, works published before 1927 are public domain; Presentation of Self in Everyday Life (1959) and Stigma (1963) remain under copyright. Treating as mostly_clear given widespread academic use and paraphrase acceptability; do not reproduce extended passages.",
        "production_ready": True,
    },
    "durkheim": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1917. All works public domain in all major jurisdictions.",
        "production_ready": True,
    },
    "max_weber": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1920. All works public domain in all major jurisdictions. Note: some English translations of Weber remain under translator copyright.",
        "production_ready": True,
    },
    "mauss": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1950. The Essay on the Gift (1925) and other works are public domain in most jurisdictions; life-plus-70 rule means EU public domain from 2020. All works clear for production.",
        "production_ready": True,
    },
    "levi_strauss": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 2009. Tristes Tropiques (1955), Structural Anthropology (1958), and Mythologiques (1964–71) remain under copyright in all major jurisdictions until 2079. Do not reproduce extended passages. Paraphrase and reference to documented structural arguments is acceptable.",
        "production_ready": False,
    },
    "margaret_mead": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1978. Coming of Age in Samoa (1928) is in a complex copyright position in the US — published 1928, copyright renewal status requires verification. Later works remain under copyright until 2048. Treat Coming of Age in Samoa as review_needed for extended reproduction; paraphrase and reference to documented positions is acceptable across all works.",
        "production_ready": True,
    },
    "ruth_benedict": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1948. Patterns of Culture (1934) — copyright renewal status requires verification for US public domain; in EU, public domain from 2018. The Chrysanthemum and the Sword (1946) — public domain in EU from 2018, US status requires verification. Treating as mostly_clear; do not reproduce extended passages without confirming US copyright renewal status.",
        "production_ready": True,
    },
    "malinowski": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1942. Argonauts of the Western Pacific (1922) and Coral Gardens and Their Magic (1935) are public domain in most jurisdictions. The posthumously published diary (1967) carries its own copyright but the underlying diary content predates 1942. Core ethnographic works clear for production.",
        "production_ready": True,
    },
    "mary_douglas": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 2007. Purity and Danger (1966), Natural Symbols (1970), and Risk and Culture (1982) remain under copyright in all major jurisdictions until 2077. Do not reproduce extended passages. Paraphrase and reference to documented analytical frameworks is acceptable.",
        "production_ready": False,
    },
    "geertz": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 2006. The Interpretation of Cultures (1973), Local Knowledge (1983), and Works and Lives (1988) remain under copyright in all major jurisdictions until 2076. Do not reproduce extended passages. Paraphrase and reference to documented methodological positions is acceptable.",
        "production_ready": False,
    },
    "saussure": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1913. Course in General Linguistics was compiled and published in 1916 — public domain in all major jurisdictions. Note: some modern critical editions with scholarly apparatus carry editor copyright on the apparatus, not the underlying text.",
        "production_ready": True,
    },
    "jakobson": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 1982. Selected Writings (8 vols.) and collected essays remain under copyright in most jurisdictions until 2052. Major essays including Linguistics and Poetics (1960) may have varying status depending on original publication venue. Paraphrase and reference to documented linguistic frameworks is acceptable; do not reproduce extended passages.",
        "production_ready": False,
    },
    "sapir": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1939. Language (1921) is public domain in all major jurisdictions. Selected Writings in Language Culture and Personality (1949, posthumous) — copyright on the editorial compilation may persist in some jurisdictions but underlying texts are clear. Core works clear for production.",
        "production_ready": True,
    },
    "zellig_harris": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 1992. Methods in Structural Linguistics (1951) and papers on transformational analysis remain under copyright in most jurisdictions until 2062. Paraphrase and reference to documented linguistic methods is acceptable; do not reproduce extended passages.",
        "production_ready": False,
    },
    "hobsbawm": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 2012. The Age of Revolution (1962), Age of Capital (1975), Age of Empire (1987), and Age of Extremes (1994) remain under copyright in all major jurisdictions until 2082. The Invention of Tradition (1983, co-edited with Terence Ranger) similarly. Do not reproduce extended passages. Paraphrase and reference to documented historical arguments is acceptable.",
        "production_ready": False,
    },
    "marc_bloch": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1944. Feudal Society (1939–40) and The Historian's Craft (1949, posthumous) are public domain in EU from 2014; US status of Historian's Craft (first English translation 1953) requires verification. Treating core historical works as public domain; exercise caution with posthumous translated editions.",
        "production_ready": True,
    },
    "braudel": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 1985. The Mediterranean (1949, revised 1966), Civilization and Capitalism (1979), and The Identity of France (1986) remain under copyright in all major jurisdictions until 2055. Do not reproduce extended passages. Paraphrase and reference to documented historical arguments is acceptable.",
        "production_ready": False,
    },
    "toynbee": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1975. A Study of History (vols. 1–6, 1934–39) may be approaching public domain in some jurisdictions; vols. 7–10 (1954) and vol. 12 (1961) remain under copyright until 2045. The abridged one-volume edition (1946, 1957) similarly. Treating as mostly_clear; do not reproduce extended passages from post-1928 volumes without verification.",
        "production_ready": True,
    },
    "huizinga": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1945. The Autumn of the Middle Ages (1919) and Homo Ludens (1938) are public domain in EU from 2015. US copyright status of Homo Ludens depends on 1950 English translation renewal — underlying Dutch text clear. Core works clear for production.",
        "production_ready": True,
    },
    "aby_warburg": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1929. All published works and the Mnemosyne Atlas (assembled 1924–29) are public domain in all major jurisdictions. The Warburg Institute holds some archival materials under separate arrangements but published scholarly legacy is clear.",
        "production_ready": True,
    },
    "mcluhan": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 1980. The Gutenberg Galaxy (1962), Understanding Media (1964), and The Medium is the Massage (1967) remain under copyright in most jurisdictions until 2050. The McLuhan estate actively manages reproduction rights. Do not reproduce extended passages. Paraphrase and reference to documented media theory positions is acceptable.",
        "production_ready": False,
    },
    "lewis_mumford": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1990. Technics and Civilization (1934) — US copyright renewal status requires verification; may be public domain. The City in History (1961) and The Myth of the Machine (1967–70) remain under copyright until 2060. Treating as mostly_clear for works before 1950; review_needed for later works. Paraphrase acceptable throughout.",
        "production_ready": True,
    },
    "norbert_elias": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 1990. The Civilizing Process (German original 1939, English translation 1969–82) — original German text approaches public domain in EU (2060); English translations remain under translator copyright. The Court Society (1969) and What is Sociology? (1970) similarly. Do not reproduce extended passages. Paraphrase and reference to documented sociological concepts is acceptable.",
        "production_ready": False,
    },
    "raymond_williams": {
        "living": False,
        "copyright_status": "review_needed",
        "copyright_notes": "Died 1988. Culture and Society (1958), The Long Revolution (1961), Marxism and Literature (1977), and Keywords (1976, revised 1983) remain under copyright in all major jurisdictions until 2058. Do not reproduce extended passages. Paraphrase and reference to documented cultural materialist positions is acceptable.",
        "production_ready": False,
    },
    'chanel': {
        "living": False,
        "copyright_status": 'review_needed',
        "copyright_notes": 'Died 1971. Chanel S.A. holds trademark and brand rights; commercial likeness use requires clearance.',
        "production_ready": False
    },
    'douglass': {
        "living": False,
        "copyright_status": 'public_domain',
        "copyright_notes": 'Died 1895. No IP concerns.',
        "production_ready": True
    },
    'du_bois': {
        "living": False,
        "copyright_status": 'mostly_clear',
        "copyright_notes": 'Died 1963. NAACP holds some archival materials; works entering public domain. Educational use clear.',
        "production_ready": True
    },

}
