COMPLIANCE_PHYSICS = {
    "heisenberg": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1976. Published writings may have copyright. Soul prompt uses public domain historical record and documented positions.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "schrodinger": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1961. 'What Is Life?' and other works may retain copyright in some jurisdictions.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "dirac": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1984. Some published works still in copyright. Historical positions well-documented.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "born": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1970. Einstein-Born letters published; some works may retain copyright.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "fermi": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1954. Historical record well-documented. Nuclear program involvement is public record.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "oppenheimer": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1967. Security hearing transcripts are public record. Bhagavad Gita quote is public domain.",
        "production_ready": True,
        "high_sensitivity": True,
    },
    "meitner": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1968. Nobel omission is documented historical record. Correspondence partially published.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "noether": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1935. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "boltzmann": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1906. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "mach": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1916. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "kelvin": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1907. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "lavoisier": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1794. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "dalton": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1844. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "priestley": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1804. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "avogadro": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1856. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "pauling": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1994. Some published works in copyright. Vitamin C advocacy is well-documented public record.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "hodgkin": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1994. Published works may retain copyright. Historical positions well-documented.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "lamarck": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1829. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "wallace": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1913. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "huxley": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1895. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "virchow": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1902. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "koch": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1910. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "fleming": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1955. Some works may retain copyright. Nobel lecture is well-documented public record.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "watson": {
        "living": True,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Living as of 2024 (born 1928). 'The Double Helix' in copyright. Race statements are documented public record.",
        "production_ready": True,
        "high_sensitivity": True,
    },
    "crick": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 2004. Published works may retain copyright. Historical positions well-documented.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "euler": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1783. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "gauss": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1855. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "riemann": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1866. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "hilbert": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1943. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "poincare": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1912. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "godel": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1978. Published works may retain copyright. Incompleteness theorems are mathematical results, not copyrightable.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "turing": {
        "living": False,
        "copyright_status": "mostly_clear",
        "copyright_notes": "Died 1954. Published works may retain copyright. Prosecution and pardon are documented public record.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "cantor": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1918. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "descartes": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1650. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
    "fermat": {
        "living": False,
        "copyright_status": "public_domain",
        "copyright_notes": "Died 1665. All works public domain.",
        "production_ready": True,
        "high_sensitivity": False,
    },
}
